---
# This handler (i.e. a task triggered by a notify) uses the 
# junos_install_config module to apply the configuration to the device
- name: Pushing config ... please wait 
  junos_install_config: >
    host={{ inventory_hostname }}
    user=jnpr
    passwd=pass123
    file={{ junos_conf }}
    overwrite=yes
    logfile=logs/{{ inventory_hostname }}.log
