---
- set_fact: 
    build_dir: build/{{ inventory_hostname }}/tmp
    junos_conf: build/{{ inventory_hostname}}/junos.conf

- name: Building common configuration
  template: >
    src=main.conf.j2
    dest={{ build_dir }}/common.conf.part