host:
  management:
    ip: 10.0.255.1
  loopback:
    ip: 192.168.255.1
  core_interfaces:
    ge-0/0/0:
      ip: 10.1.0.0
    ge-0/0/1:
      ip: 10.1.0.2
  agg_sw_interfaces:
    ge-1/0/0:
      ip: 10.1.1.0
